Better format for the anon-verify report

diff --git a/usr/bin/anon-verify b/usr/bin/anon-verify
--- a/usr/bin/anon-verify
+++ b/usr/bin/anon-verify
@@ -78,29 +78,31 @@ function get_tor_start_command() {
 ## $tor_verify_config_output and $tor_verify_config_exit_code
 function generate_report() {
     ## generate concise report
-    if [ "$tor_verify_config_exit_code" = "0" ]; then
-        tor_verify_config_output_concise="Tor configuration was valid."
-        anon_verify_report="=====================================================================
-Tor Config Check Result: (Tor verify exit code: $tor_verify_config_exit_code)
-No error detected in your Tor configuration.
-=====================================================================
-Tor full reports:
-$tor_verify_config_output
-====================================================================="
-    else
-        ## concise report which only contains complains with [warn] or [err] tags
-        tor_verify_config_output_concise="$(grep -E -w -h -i '\[warn\]|\[err\]' <<< "$tor_verify_config_output" 2>&1)" || true
-        anon_verify_report="=====================================================================
-Tor Config Check Result: (Tor verify exit code: $tor_verify_config_exit_code)
-Your Tor config file contains at least one error.
-=====================================================================
-Tor concise reports (below warns and errors must be fixed before you can use Tor):
-$tor_verify_config_output_concise
+    echo "/===================================================================\\"
+    echo "|                      Report Summary                               |"
+    echo "\\===================================================================/"
 
-Tor full reports:
-$tor_verify_config_output
-"
+    if [ "$tor_verify_config_exit_code" = "0" ]; then
+        echo "No error detected in your Tor configuration."
+        echo "Tor verify exit code: $tor_verify_config_exit_code"
+        tor_verify_config_output_concise="Tor configuration was valid."
+    else
+        echo "Your Tor config file contains at least one error."
+        echo "Tor verify exit code: $tor_verify_config_exit_code"
+
+        ## concise report which only contains complains with [warn] or [err] tags
+        echo "/===================================================================\\"
+        echo "|                    Tor Concise Report                             |"
+        echo "\\===================================================================/"
+        echo "Below warns and errors must be fixed before you can use Tor:"
+        grep -E -w -h -i --color '\[warn\]|\[err\]' <<< "$tor_verify_config_output"
+        tor_verify_config_output_concise="$(grep -E -w -h -i --color '\[warn\]|\[err\]' <<< "$tor_verify_config_output" 2>&1)" || true
     fi
+
+    echo "/===================================================================\\"
+    echo "|                      Tor Full Report                              |"
+    echo "\\===================================================================/"
+    echo "$tor_verify_config_output"
 
     ## TODO: $anon_verify_report_html is used by whonixcheck
     ## we need to find a way to merge it with $anon_verify_report
@@ -132,9 +134,6 @@ $start_menu_instructions_system_first_part Terminal
 <blockquote>    $start_menu_instructions_system_first_part Restart Tor</blockquote>
     <br></br>or in Terminal: <code>sudo service tor@default restart</code></p>"
 
-    ## print out the report
-    echo "$anon_verify_report"
-
     ## torrc-parser will grep the invalid option for user and specify
     ## which file is corrupted for better fixing suggestion
     source /usr/lib/anon-gw-anonymizer-config/torrc-parser
@@ -151,16 +150,16 @@ $start_menu_instructions_system_first_part Terminal
     # call parser() to parse torrc files, arguments order matters
     parser "$default_torrc" "$f_torrc"
 
-    echo "====================================================================="
-    echo "================= Used Tor Configuration Files  ====================="
-    echo "====================================================================="
+    echo "/===================================================================\\"
+    echo "|                 Used Tor Configuration Files                      |"
+    echo "\\===================================================================/"
     used_torrc_files
 
     ## extract the unknown option complained by Tor
     if [[ "$tor_verify_config_output" =~ (Unknown option \')([^\']*) ]]; then
-	echo "====================================================================="
-        echo "================== Detailed Suggested Solution  ====================="
-        echo "====================================================================="
+	echo "/===================================================================\\"
+        echo "|                 Detailed Suggested Solution                       |"
+        echo "\\===================================================================/"
 	unknown_option_specifier "${BASH_REMATCH[2]}"
     fi
 
@@ -169,9 +168,9 @@ $start_menu_instructions_system_first_part Terminal
     ## only use it with anon-verify -v
     ## we use anon-verify -vv to show lines starts with # also
     if [ "$VERBOSE" = "1" ]; then
-        echo "====================================================================="
-        echo "=============== Verbose Tor Configuration Parsing  =================="
-        echo "====================================================================="
+        echo "/===================================================================\\"
+        echo "|                Verbose Tor Configuration Parsing                  |"
+        echo "\\===================================================================/"
         parsing_order_verbose
     fi
 
